### ISSUE TITLE
Setup two server instances for ADV and AVV

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-server#359]
As a developer I would like to have a clear strategy how 2 parallel server instances can run on the same host machine.
Research on the local developer system needs to be done for how to do this.

1. default instance: mibi-portal-server current develop version for AVV, excel v17
2. instance: mibi-portal-server current production version for ADV, excel v16
 
Each instance will run on a different port. The default system will check the version of the uploaded excel sheet. This check happens at the corresponding endpoint. If the excel sheet is version 16 the request is forwarded to the 2. server instance that handles the ADV codes which is the current production system.

**Comment by birgitlewicki** [comment]
technical solution not yet found
-> needs further discussion

**Comment by birgitlewicki** [comment]
Decision for the setup:
- The AVV mibi server instance with the AVV client will run on the current productive host.
-  The ADV mibi server instance with the ADV client (current production system) will run on the nolar dev host with a changed URL.
-  When the user uploads an ADV v16 excel sheet to the AVV server he will get a popup with an explanation and a link to the ADV mibi server

**Comment by birgitlewicki** [comment]
On the dev version of nolar now the current productive adv mibi-portal system is installed for testing. It works currently with a database that has old an scrumbled data in, but should be ok for testing.

**Comment by afalenski** [comment]
- Einsendebogen v16 upload works
- Data is shown correctly in the client
- BfR lab is recognised due to stated pathogen
- Login works
- Wizard shows methods for the respective lab, shows message at "sonstiges" and message at "Vergleiche mit humanen Isolaten"
- E-Mail window opens
- Send button works
- Email sent by MiBi-Portal to the BfR lab has the correct format in subject and text
- Email to the BfR lab contains correct Excel format, data and layout
- Email sent by MiBi-Portal to the user has the correct format in subject and text
- Email to the user contains correct data in PDF

**Bug:** 
PDF sent by MiBi-Portal does not look as it should: 2 lines of text from the first page are on a second page which is mostly empty. Data appears on the third page.
