### ISSUE TITLE
Provide sneaky registration feature for the parse server

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#381]

**Comment by afalenski** [comment]
- After the first login (since implementation of this feature) of a user who was already in the DB a new entry is made in the _User table.
- Email and first login date and time are shown.
- The same is true if a new user registers and then logs in.
- Several logins of the same user do not result in duplicate rows. Each user added is only once to the _User table.

Bug:
- The counter next to "_User", showing how many users have been entered into this table, does not count. It shows two entries although there are four (see four rows on the right in the screenshot). Please fix.

<img width="342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce974a2f52c30a6a4e541d176733e20cabd7490a/grafik.png" alt="grafik.png" />

**Comment by dptolle** [comment]
@afalenski That fix needs to be implmented by the parse dashboard team.  Maybe send them a bug report?

**Comment by afalenski** [comment]
I think issue https://github.com/parse-community/parse-dashboard/issues/2502 might cover our case.
