### ISSUE TITLE
Adding further autocorrections (blue color)

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-server#68]
@draaw commented on [Sun Oct 21 2018](https://github.com/SiLeBAT/mibi-portal-client/issues/117)

As a portal user I would like to have autocorrections where meaningful - see old server autocorrections

- [x] ADV-16 (3): Autocorrect number codes ONLY - do regular expression & replace with string 
- [x] ADV-9 (7): RegEx
- [x] PLZ (8): Do Not Autocorrect!
- [x] ADV-2 (10): check ADV-3 first (& Autocorrect with REGEX) then either Autocorrect (if 1), accept or flag as error
- [x] ADV-3 (11): Regex
- [x] ADV-12 (13): RegEx or replace string
- [x] ADv-8(16): RegEx

---

@dptolle commented on [Wed Oct 24 2018](https://github.com/SiLeBAT/mibi-portal-client/issues/117#issuecomment-432597749)

[Mibi-Portal_Fehlermeldungen_AF1.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/2510022/Mibi-Portal_Fehlermeldungen_AF1.xlsx)

**Comment by draaw** [comment]
tiny bug:
- upload a file with "01" in column ADV-Nr2
- change "01" to "1"
- validate (leads to blue autocorrection)
- validate (leads to acceptance of autocorrected value)
- there is still a grey tooltip saying "Ursprünglich: 01" - but the actual value is also "01". So why the grey tooltip? Wouldn't it make sense to always compare the altered value with initial value to decide about showing the grey tooltip?

**Comment by afalenski** [comment]
- [x] Problem noted by AAW is solved

ADV16
- [x] Missing first 0 is corrected and codes are replaced with ADV16 text, whitespace is tolerated

ADV9 codes
- [x] Missing first 0 and "xxx" are corrected
- [ ] A whitespace is not tolerated

PLZ
- [x] No corrections as intended; correct postal codes are recognised (number consisting of 5 digits)
- [ ] A whitespace is not tolerated

ADV2 and 3:
[MiBi-TEST_ADV2u3x23-8.xlsx](https://github.com/SiLeBAT/mibi-portal-server/files/2566039/MiBi-TEST_ADV2u3x23-8.xlsx)
- [x] Contrary to the ticket text 1 is NOT autocorrected; but it is OK, because we cannot guess whether the user omitted the first 0 (-> 01) or forgot the 5 (-> 15).
- [ ] Leading 0 in ADV3 produces a **MiBi-Portal Error**, see https://github.com/SiLeBAT/mibi-portal-client/issues/138
- [ ] ADV2 belongs to the matrix. Please dye also this cell in red if the matrix is completely missing (see Probennummer 5 and 11 in the above test sheet)
- [ ] If ADV3 is unique and ADV2 is missing please add ADV2 (see Probennummer 16)

ADV12
- [x] Missing first 0 is corrected, ADV12 text is replaced with its code, a whitespace is tolerated.

ADV8
- [x] Abbreviations with "x" are corrected
- [ ] A whitespace is not tolerated
- [ ] ADV8 text is not replaced with its code. Should we offer this feature?

All test sheets are on the internal network folder.

**Comment by afalenski** [comment]
Very nice.
